### ISSUE TITLE
Unclear where experiments folder is

### ISSUE THREAD

**Issue by equaeghe** [deeprob-org/deeprob-kit#6]
I installed deeprob-kit using pip:
```
$ pip install --user deeprob-kit
```
Now, I want try out the experiments to see if the code works on my system. However, I do not seem to have the `experiments` folder and therefore do not seem to be able to run them or put the datasets in place. Namely, what I have after installation is the following tree:
```
~/.local/lib/python3.9 $ tree -L 3
.
└── site-packages
    ├── deeprob
    │   ├── __init__.py
    │   ├── __pycache__
    │   ├── context.py
    │   ├── flows
    │   ├── spn
    │   ├── torch
    │   └── utils
    └── deeprob_kit-1.0.0.dist-info
        ├── INSTALLER
        ├── LICENSE
        ├── METADATA
        ├── RECORD
        ├── REQUESTED
        ├── WHEEL
        └── top_level.txt

8 directories, 9 files
```
My impression is that the bundle on PyPi only contains deeprob-kit itself, without any of the other materials. Perhaps putting the experiments folder (and others) under `deeprob` may provide a solution, but I guess you chose the current structure for a reason. Or perhaps I am looking in the wrong location.

**Comment by loreloc** [comment]
The PIP package contains only the `deeprob` module, i.e. the library without examples, unit tests, benchmark and experiments. I didn't put those directories because I thought a PIP package of a library shouldn't contain development and experiments related code, since they are not part of the library itself.

However, if you wish to run the experiments (and examples), probably it's better to clone the repository and work from that.

**Comment by loreloc** [comment]
Sounds good, so this issue is related to #3.
